### PR TITLE
Change domain/common to domain if we have an URI scheme match

### PR DESCRIPTION
**Pull request by snan**
Also add "edu".

### CODE REVIEW

**Comment by ashinn** [comment]
Thanks!

**Comment by sjamaan** [comment]
Shouldn't we get rid of `top-level-domain` and `domain/common` at all, now? These are undocumented and I thought only for internal use.

**Comment by snan** [comment]
They are useful when there isn't a preceding https://.

**Comment by sjamaan** [comment]
Should we document them as officially supported instead, then?

**Comment by ashinn** [comment]
Yes, it's effectively exported even if undocumented, hard to say who's using it so we can't remove it.  (Also I find it useful.)

Good to document it though.

**Comment by snan** [comment]
There's a lot of undocumented ones in the same vein, like ip-address,
email-local-part, utf8-tail-char etc.  Not sure we need to document all
of those.

**Pull request merged**
